if: |
  commit_message =~ /^Build.*:/

os: linux

dist: xenial

language: shell

git:
  depth: 2

services:
  - docker

env:
  global:
    - DOCKER_ORG=provarepro
    - DOCKER_USER=reprova
    # DOCKER_PASS="..."
    - secure: "l66P9/B9nYJkxG1inSdaO1f5//eh4vsE9ob+BweeQVXN3kUfDEctMHJ3fe1criL+GNLzMmAn4lr0Ny2BO0fQBv0LPJ7diJ75vBBRU25AYkyoFg57HkZOLL8QtEEcDT/qkGykx/QDdFm/rrDxBM6oce+6IoIT9vscwCZqTm2cW89ehevqz4k8iK+fcziQY2T5ox06N8Wue1+DUkpieIKKfa1QUMKeSHxxWiEOhPUDRVlNgMemA2A3ooo17nxYmIgeKdHZ0qPmqve6brHMCy3Riag2B8+Zi9voPw5wsT43rfaoQEtICHZrO9YRXYDuMjBPMHN/WnVcmcjXeFa6hlrolUjKS9LDzj316Mssh/icboTapxd7OyKx2OmntoWgwUVvuSa/BH9XaUxglYr79+oxD0E+gig+b9LblyA5k0UzzFQaxY7Em9uicjfxdjSNsFxFqi4omGz866XBKen39F7NEB2gxexabgEymrCb/zMyNMuginb7qgXIXzIo3BFiu0jAwt9Fm6McoTJ9cIX4+4hNffS7t1Wza75C/xAFxz7F9NEhbfoaV4w9hUDH+nzf7pP1iCmTCegPItLFUfkOZTI1ZHrIHMydiu5vzGr7KKQoZ36YqVo153hwd6KbwXVdRIgRIabbN5ZTzzv2gS7NjSU5ussxjrUhtmFgAGQGmZ9Mlkk="

jobs:
  include:
    - stage: build docker image
      if: |
        commit_message =~ /^Build docker:*/
      script:
        #Commit as Build docker: (python|cpp)/BASE_IMAGE
        - BUILD_INFO=${TRAVIS_COMMIT_MESSAGE#*"Build docker:"}
        - BUILD_INFO=`echo ${BUILD_INFO%%,*} | sed 's/ *$//g'`
        - BUILD_FLD=${BUILD_INFO%%/*}
        - BASE_IMAGE=${BUILD_INFO#*/}
        #- BASE_IMAGE=${BASE_IMAGE,,}
        - BASE_IMAGE_TAG=${BASE_IMAGE#*/}
        - BASE_IMAGE_TAG="${TRAVIS_BRANCH}-${BASE_IMAGE_TAG/:/-}"

        #IMAGE_NAME as mlperf-inference:$BRANCH-$BASE_IMAGE
        - IMAGE_NAME="${DOCKER_ORG}/mlperf-inference:${BASE_IMAGE_TAG}"

        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"

        #- docker pull ${IMAGE_NAME} || true

        - docker build
          --cache-from ${IMAGE_NAME}
          --label "BUILT-BY=Travis"
          --label "BUILT-FROM=${TRAVIS_REPO_SLUG}"
          --label "BUILD-LOG=${TRAVIS_BUILD_WEB_URL}"
          --build-arg BASE_IMAGE=${BASE_IMAGE}
          --tag ${IMAGE_NAME}
          ./${BUILD_FLD}

        - docker images

        - docker push ${IMAGE_NAME}
