if: |
  commit_message =~ /^Build.*:/

os: linux

dist: xenial

language: shell

git:
  depth: 2

services:
  - docker

env:
  global:
    - DOCKER_ORG=provarepro
    - DOCKER_USER=reprova
    # DOCKER_PASS="..."
    - secure: "o4gqlctgPlwdEAFbHLYccctkb57J5g2Tm/PL3OHggz0n4xTqp2KNh3DMbQXOIWTwKzuHpw4MoXqEaligMvq8zqOcCn0qs3yhqsVIooEq48xDyZ5B7tbNkbBdkzHIHnyJ0Kv5ZG0sX3HtfgKDCfWj/FMw9BuP13xEYsBHqKULTRvj/gqH6vKmcQuHytTzQCeQh6gZHHlO0kM53Z+84oTj0OvyihfZ4yJ8PBL923EqgM+6b8ssJjxQNx0/fOk8lxa7wsgVDAyg6nmvsqhzGGMVlgSVIJPKQAqH60xrkilMQk2SSSQONIgPEopLT+8IzZtHwRpEfwC4TOjs3Vzi7B3+mM/6kfa5tWk5zDlcI0ZvvuzxkpLCu1fHShk15nV6odR/ZoOfTvCq86dA9JzgyBciZZQIrcY8I+fOS5Kp+bVAcO9C5VuB4yYQPIEuOSLWYiJudQuNVWpH+8EmvzWACtFd+D6f7XQ/Rf2eeu0qGwhvue69IGmlqoEBWtyD8qoxg3cmoHBMeFwxyYf/gKXQRIAAIcdLRgG2U0VK0NuhgzZmIvzcrl7bZYh3IxYh7K9/8ENRV612ImbeWgdESSkdnWEoZip53USH463zJ/awZbxkiDZIEyDKXxkFiWTC7O2eVKMZGtUky53QMU9w14O8HqKu6CNzSbDQOU+CiA/iVV3bGcE="

jobs:
  include:
    - stage: build docker image
      if: |
        commit_message =~ /^Build docker:*/
      script: |
        #Commit as Build docker: (python|cpp)/BASE_IMAGE
        BUILD_INFO=${TRAVIS_COMMIT_MESSAGE#*"Build docker:"}
        BUILD_INFO=`echo ${BUILD_INFO%%,*} | sed 's/ *$//g'`
        BUILD_FLD=${BUILD_INFO%%/*}
        BASE_IMAGE=${BUILD_INFO#*/}
        #BASE_IMAGE=${BASE_IMAGE,,}

        #IMAGE_NAME as mlperf-inference:$BRANCH-$BASE-IMAGE
        IMAGE_NAME="mlperf-inference:$TRAVIS_BRANCH-$BASE-IMAGE"
        
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

        #docker pull ${IMAGE_NAME} || true

        docker build\
          --cache-from ${IMAGE_NAME}\
          --label "BUILT-BY=Travis"\
          --label "BUILT-FROM=${TRAVIS_REPO_SLUG}"\
          --label "BUILD-LOG=${TRAVIS_BUILD_WEB_URL}"\
          --build-arg BASE_IMAGE=${BASE_IMAGE}\
          --tag ${IMAGE_NAME}\
          ./${BUILD_FLD}

        docker images

        docker push ${IMAGE_NAME}
